# Site settings
title: Travorama
email: mohamed.zarrouk@ext.daint-gobain.com
description: Travorma Static Front.
baseurl: "/fr
url: ""
twitter_username: 
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Zarrouk Mohamed" # Set default author name
      categories: "travaux"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
